// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PuzzleGameProto.proto

package com.pcer.puzzlegame.proto;

public final class PuzzleGameProto {
  private PuzzleGameProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PuzzleGameUserInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PuzzleGameUserInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string username = 1;</code>
     */
    boolean hasUsername();
    /**
     * <code>optional string username = 1;</code>
     */
    java.lang.String getUsername();
    /**
     * <code>optional string username = 1;</code>
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    /**
     * <code>optional string nickname = 2;</code>
     */
    boolean hasNickname();
    /**
     * <code>optional string nickname = 2;</code>
     */
    java.lang.String getNickname();
    /**
     * <code>optional string nickname = 2;</code>
     */
    com.google.protobuf.ByteString
        getNicknameBytes();

    /**
     * <code>optional string password = 3;</code>
     */
    boolean hasPassword();
    /**
     * <code>optional string password = 3;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>optional string password = 3;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>optional int32 scores = 4;</code>
     */
    boolean hasScores();
    /**
     * <code>optional int32 scores = 4;</code>
     */
    int getScores();
  }
  /**
   * Protobuf type {@code PuzzleGameUserInfo}
   */
  public  static final class PuzzleGameUserInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PuzzleGameUserInfo)
      PuzzleGameUserInfoOrBuilder {
    // Use PuzzleGameUserInfo.newBuilder() to construct.
    private PuzzleGameUserInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PuzzleGameUserInfo() {
      username_ = "";
      nickname_ = "";
      password_ = "";
      scores_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PuzzleGameUserInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              username_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              nickname_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              password_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              scores_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pcer.puzzlegame.proto.PuzzleGameProto.internal_static_PuzzleGameUserInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pcer.puzzlegame.proto.PuzzleGameProto.internal_static_PuzzleGameUserInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo.class, com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo.Builder.class);
    }

    private int bitField0_;
    public static final int USERNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object username_;
    /**
     * <code>optional string username = 1;</code>
     */
    public boolean hasUsername() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string username = 1;</code>
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          username_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string username = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NICKNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object nickname_;
    /**
     * <code>optional string nickname = 2;</code>
     */
    public boolean hasNickname() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string nickname = 2;</code>
     */
    public java.lang.String getNickname() {
      java.lang.Object ref = nickname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nickname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string nickname = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNicknameBytes() {
      java.lang.Object ref = nickname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 3;
    private volatile java.lang.Object password_;
    /**
     * <code>optional string password = 3;</code>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string password = 3;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string password = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCORES_FIELD_NUMBER = 4;
    private int scores_;
    /**
     * <code>optional int32 scores = 4;</code>
     */
    public boolean hasScores() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 scores = 4;</code>
     */
    public int getScores() {
      return scores_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, username_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, nickname_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, password_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, scores_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, username_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, nickname_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, password_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, scores_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PuzzleGameUserInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PuzzleGameUserInfo)
        com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pcer.puzzlegame.proto.PuzzleGameProto.internal_static_PuzzleGameUserInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pcer.puzzlegame.proto.PuzzleGameProto.internal_static_PuzzleGameUserInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo.class, com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo.Builder.class);
      }

      // Construct using com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        username_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        nickname_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        scores_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pcer.puzzlegame.proto.PuzzleGameProto.internal_static_PuzzleGameUserInfo_descriptor;
      }

      public com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo getDefaultInstanceForType() {
        return com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo.getDefaultInstance();
      }

      public com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo build() {
        com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo buildPartial() {
        com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo result = new com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.username_ = username_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.nickname_ = nickname_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.password_ = password_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.scores_ = scores_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo) {
          return mergeFrom((com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo other) {
        if (other == com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo.getDefaultInstance()) return this;
        if (other.hasUsername()) {
          bitField0_ |= 0x00000001;
          username_ = other.username_;
          onChanged();
        }
        if (other.hasNickname()) {
          bitField0_ |= 0x00000002;
          nickname_ = other.nickname_;
          onChanged();
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00000004;
          password_ = other.password_;
          onChanged();
        }
        if (other.hasScores()) {
          setScores(other.getScores());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object username_ = "";
      /**
       * <code>optional string username = 1;</code>
       */
      public boolean hasUsername() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string username = 1;</code>
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            username_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string username = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string username = 1;</code>
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        username_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string username = 1;</code>
       */
      public Builder clearUsername() {
        bitField0_ = (bitField0_ & ~0x00000001);
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      /**
       * <code>optional string username = 1;</code>
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        username_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nickname_ = "";
      /**
       * <code>optional string nickname = 2;</code>
       */
      public boolean hasNickname() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string nickname = 2;</code>
       */
      public java.lang.String getNickname() {
        java.lang.Object ref = nickname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            nickname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string nickname = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNicknameBytes() {
        java.lang.Object ref = nickname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nickname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string nickname = 2;</code>
       */
      public Builder setNickname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        nickname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string nickname = 2;</code>
       */
      public Builder clearNickname() {
        bitField0_ = (bitField0_ & ~0x00000002);
        nickname_ = getDefaultInstance().getNickname();
        onChanged();
        return this;
      }
      /**
       * <code>optional string nickname = 2;</code>
       */
      public Builder setNicknameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        nickname_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>optional string password = 3;</code>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string password = 3;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            password_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string password = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string password = 3;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 3;</code>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000004);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 3;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        password_ = value;
        onChanged();
        return this;
      }

      private int scores_ ;
      /**
       * <code>optional int32 scores = 4;</code>
       */
      public boolean hasScores() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 scores = 4;</code>
       */
      public int getScores() {
        return scores_;
      }
      /**
       * <code>optional int32 scores = 4;</code>
       */
      public Builder setScores(int value) {
        bitField0_ |= 0x00000008;
        scores_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 scores = 4;</code>
       */
      public Builder clearScores() {
        bitField0_ = (bitField0_ & ~0x00000008);
        scores_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PuzzleGameUserInfo)
    }

    // @@protoc_insertion_point(class_scope:PuzzleGameUserInfo)
    private static final com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo();
    }

    public static com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<PuzzleGameUserInfo>
        PARSER = new com.google.protobuf.AbstractParser<PuzzleGameUserInfo>() {
      public PuzzleGameUserInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new PuzzleGameUserInfo(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<PuzzleGameUserInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PuzzleGameUserInfo> getParserForType() {
      return PARSER;
    }

    public com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PuzzleGameMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PuzzleGameMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .PuzzleGameMessage.MesType mesType = 1;</code>
     */
    boolean hasMesType();
    /**
     * <code>required .PuzzleGameMessage.MesType mesType = 1;</code>
     */
    com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage.MesType getMesType();

    /**
     * <code>repeated .PuzzleGameUserInfo pUser = 2;</code>
     */
    java.util.List<com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo> 
        getPUserList();
    /**
     * <code>repeated .PuzzleGameUserInfo pUser = 2;</code>
     */
    com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo getPUser(int index);
    /**
     * <code>repeated .PuzzleGameUserInfo pUser = 2;</code>
     */
    int getPUserCount();
    /**
     * <code>repeated .PuzzleGameUserInfo pUser = 2;</code>
     */
    java.util.List<? extends com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfoOrBuilder> 
        getPUserOrBuilderList();
    /**
     * <code>repeated .PuzzleGameUserInfo pUser = 2;</code>
     */
    com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfoOrBuilder getPUserOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code PuzzleGameMessage}
   */
  public  static final class PuzzleGameMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PuzzleGameMessage)
      PuzzleGameMessageOrBuilder {
    // Use PuzzleGameMessage.newBuilder() to construct.
    private PuzzleGameMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PuzzleGameMessage() {
      mesType_ = 0;
      pUser_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PuzzleGameMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage.MesType value = com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage.MesType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                mesType_ = rawValue;
              }
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                pUser_ = new java.util.ArrayList<com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo>();
                mutable_bitField0_ |= 0x00000002;
              }
              pUser_.add(input.readMessage(com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          pUser_ = java.util.Collections.unmodifiableList(pUser_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pcer.puzzlegame.proto.PuzzleGameProto.internal_static_PuzzleGameMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pcer.puzzlegame.proto.PuzzleGameProto.internal_static_PuzzleGameMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage.class, com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage.Builder.class);
    }

    /**
     * Protobuf enum {@code PuzzleGameMessage.MesType}
     */
    public enum MesType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>REGREQ = 0;</code>
       *
       * <pre>
       *for register
       * </pre>
       */
      REGREQ(0, 0),
      /**
       * <code>REGACK = 1;</code>
       */
      REGACK(1, 1),
      /**
       * <code>REGNEG = 2;</code>
       */
      REGNEG(2, 2),
      /**
       * <code>LOGREQ = 3;</code>
       *
       * <pre>
       *for login
       * </pre>
       */
      LOGREQ(3, 3),
      /**
       * <code>LOGACK = 4;</code>
       */
      LOGACK(4, 4),
      /**
       * <code>LOGNEG = 5;</code>
       */
      LOGNEG(5, 5),
      /**
       * <code>SUBREQ = 6;</code>
       *
       * <pre>
       *for submit scores
       * </pre>
       */
      SUBREQ(6, 6),
      /**
       * <code>SUBACK = 7;</code>
       */
      SUBACK(7, 7),
      /**
       * <code>RANKREQ = 8;</code>
       *
       * <pre>
       *for get ranks
       * </pre>
       */
      RANKREQ(8, 8),
      /**
       * <code>RANKACK = 9;</code>
       */
      RANKACK(9, 9),
      /**
       * <code>MODREQ = 10;</code>
       *
       * <pre>
       *for modify personal information
       * </pre>
       */
      MODREQ(10, 10),
      /**
       * <code>MODACK = 11;</code>
       */
      MODACK(11, 11),
      /**
       * <code>MODNEG = 12;</code>
       */
      MODNEG(12, 12),
      ;

      /**
       * <code>REGREQ = 0;</code>
       *
       * <pre>
       *for register
       * </pre>
       */
      public static final int REGREQ_VALUE = 0;
      /**
       * <code>REGACK = 1;</code>
       */
      public static final int REGACK_VALUE = 1;
      /**
       * <code>REGNEG = 2;</code>
       */
      public static final int REGNEG_VALUE = 2;
      /**
       * <code>LOGREQ = 3;</code>
       *
       * <pre>
       *for login
       * </pre>
       */
      public static final int LOGREQ_VALUE = 3;
      /**
       * <code>LOGACK = 4;</code>
       */
      public static final int LOGACK_VALUE = 4;
      /**
       * <code>LOGNEG = 5;</code>
       */
      public static final int LOGNEG_VALUE = 5;
      /**
       * <code>SUBREQ = 6;</code>
       *
       * <pre>
       *for submit scores
       * </pre>
       */
      public static final int SUBREQ_VALUE = 6;
      /**
       * <code>SUBACK = 7;</code>
       */
      public static final int SUBACK_VALUE = 7;
      /**
       * <code>RANKREQ = 8;</code>
       *
       * <pre>
       *for get ranks
       * </pre>
       */
      public static final int RANKREQ_VALUE = 8;
      /**
       * <code>RANKACK = 9;</code>
       */
      public static final int RANKACK_VALUE = 9;
      /**
       * <code>MODREQ = 10;</code>
       *
       * <pre>
       *for modify personal information
       * </pre>
       */
      public static final int MODREQ_VALUE = 10;
      /**
       * <code>MODACK = 11;</code>
       */
      public static final int MODACK_VALUE = 11;
      /**
       * <code>MODNEG = 12;</code>
       */
      public static final int MODNEG_VALUE = 12;


      public final int getNumber() {
        return value;
      }

      public static MesType valueOf(int value) {
        switch (value) {
          case 0: return REGREQ;
          case 1: return REGACK;
          case 2: return REGNEG;
          case 3: return LOGREQ;
          case 4: return LOGACK;
          case 5: return LOGNEG;
          case 6: return SUBREQ;
          case 7: return SUBACK;
          case 8: return RANKREQ;
          case 9: return RANKACK;
          case 10: return MODREQ;
          case 11: return MODACK;
          case 12: return MODNEG;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MesType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MesType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MesType>() {
              public MesType findValueByNumber(int number) {
                return MesType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final MesType[] VALUES = values();

      public static MesType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MesType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:PuzzleGameMessage.MesType)
    }

    private int bitField0_;
    public static final int MESTYPE_FIELD_NUMBER = 1;
    private int mesType_;
    /**
     * <code>required .PuzzleGameMessage.MesType mesType = 1;</code>
     */
    public boolean hasMesType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .PuzzleGameMessage.MesType mesType = 1;</code>
     */
    public com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage.MesType getMesType() {
      com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage.MesType result = com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage.MesType.valueOf(mesType_);
      return result == null ? com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage.MesType.REGREQ : result;
    }

    public static final int PUSER_FIELD_NUMBER = 2;
    private java.util.List<com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo> pUser_;
    /**
     * <code>repeated .PuzzleGameUserInfo pUser = 2;</code>
     */
    public java.util.List<com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo> getPUserList() {
      return pUser_;
    }
    /**
     * <code>repeated .PuzzleGameUserInfo pUser = 2;</code>
     */
    public java.util.List<? extends com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfoOrBuilder> 
        getPUserOrBuilderList() {
      return pUser_;
    }
    /**
     * <code>repeated .PuzzleGameUserInfo pUser = 2;</code>
     */
    public int getPUserCount() {
      return pUser_.size();
    }
    /**
     * <code>repeated .PuzzleGameUserInfo pUser = 2;</code>
     */
    public com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo getPUser(int index) {
      return pUser_.get(index);
    }
    /**
     * <code>repeated .PuzzleGameUserInfo pUser = 2;</code>
     */
    public com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfoOrBuilder getPUserOrBuilder(
        int index) {
      return pUser_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMesType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, mesType_);
      }
      for (int i = 0; i < pUser_.size(); i++) {
        output.writeMessage(2, pUser_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, mesType_);
      }
      for (int i = 0; i < pUser_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, pUser_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PuzzleGameMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PuzzleGameMessage)
        com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pcer.puzzlegame.proto.PuzzleGameProto.internal_static_PuzzleGameMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pcer.puzzlegame.proto.PuzzleGameProto.internal_static_PuzzleGameMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage.class, com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage.Builder.class);
      }

      // Construct using com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPUserFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        mesType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (pUserBuilder_ == null) {
          pUser_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          pUserBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pcer.puzzlegame.proto.PuzzleGameProto.internal_static_PuzzleGameMessage_descriptor;
      }

      public com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage getDefaultInstanceForType() {
        return com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage.getDefaultInstance();
      }

      public com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage build() {
        com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage buildPartial() {
        com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage result = new com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.mesType_ = mesType_;
        if (pUserBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            pUser_ = java.util.Collections.unmodifiableList(pUser_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.pUser_ = pUser_;
        } else {
          result.pUser_ = pUserBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage) {
          return mergeFrom((com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage other) {
        if (other == com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage.getDefaultInstance()) return this;
        if (other.hasMesType()) {
          setMesType(other.getMesType());
        }
        if (pUserBuilder_ == null) {
          if (!other.pUser_.isEmpty()) {
            if (pUser_.isEmpty()) {
              pUser_ = other.pUser_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensurePUserIsMutable();
              pUser_.addAll(other.pUser_);
            }
            onChanged();
          }
        } else {
          if (!other.pUser_.isEmpty()) {
            if (pUserBuilder_.isEmpty()) {
              pUserBuilder_.dispose();
              pUserBuilder_ = null;
              pUser_ = other.pUser_;
              bitField0_ = (bitField0_ & ~0x00000002);
              pUserBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPUserFieldBuilder() : null;
            } else {
              pUserBuilder_.addAllMessages(other.pUser_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMesType()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int mesType_ = 0;
      /**
       * <code>required .PuzzleGameMessage.MesType mesType = 1;</code>
       */
      public boolean hasMesType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .PuzzleGameMessage.MesType mesType = 1;</code>
       */
      public com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage.MesType getMesType() {
        com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage.MesType result = com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage.MesType.valueOf(mesType_);
        return result == null ? com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage.MesType.REGREQ : result;
      }
      /**
       * <code>required .PuzzleGameMessage.MesType mesType = 1;</code>
       */
      public Builder setMesType(com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage.MesType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        mesType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .PuzzleGameMessage.MesType mesType = 1;</code>
       */
      public Builder clearMesType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        mesType_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo> pUser_ =
        java.util.Collections.emptyList();
      private void ensurePUserIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          pUser_ = new java.util.ArrayList<com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo>(pUser_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo, com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo.Builder, com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfoOrBuilder> pUserBuilder_;

      /**
       * <code>repeated .PuzzleGameUserInfo pUser = 2;</code>
       */
      public java.util.List<com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo> getPUserList() {
        if (pUserBuilder_ == null) {
          return java.util.Collections.unmodifiableList(pUser_);
        } else {
          return pUserBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .PuzzleGameUserInfo pUser = 2;</code>
       */
      public int getPUserCount() {
        if (pUserBuilder_ == null) {
          return pUser_.size();
        } else {
          return pUserBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .PuzzleGameUserInfo pUser = 2;</code>
       */
      public com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo getPUser(int index) {
        if (pUserBuilder_ == null) {
          return pUser_.get(index);
        } else {
          return pUserBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .PuzzleGameUserInfo pUser = 2;</code>
       */
      public Builder setPUser(
          int index, com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo value) {
        if (pUserBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePUserIsMutable();
          pUser_.set(index, value);
          onChanged();
        } else {
          pUserBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PuzzleGameUserInfo pUser = 2;</code>
       */
      public Builder setPUser(
          int index, com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo.Builder builderForValue) {
        if (pUserBuilder_ == null) {
          ensurePUserIsMutable();
          pUser_.set(index, builderForValue.build());
          onChanged();
        } else {
          pUserBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PuzzleGameUserInfo pUser = 2;</code>
       */
      public Builder addPUser(com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo value) {
        if (pUserBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePUserIsMutable();
          pUser_.add(value);
          onChanged();
        } else {
          pUserBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .PuzzleGameUserInfo pUser = 2;</code>
       */
      public Builder addPUser(
          int index, com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo value) {
        if (pUserBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePUserIsMutable();
          pUser_.add(index, value);
          onChanged();
        } else {
          pUserBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PuzzleGameUserInfo pUser = 2;</code>
       */
      public Builder addPUser(
          com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo.Builder builderForValue) {
        if (pUserBuilder_ == null) {
          ensurePUserIsMutable();
          pUser_.add(builderForValue.build());
          onChanged();
        } else {
          pUserBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PuzzleGameUserInfo pUser = 2;</code>
       */
      public Builder addPUser(
          int index, com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo.Builder builderForValue) {
        if (pUserBuilder_ == null) {
          ensurePUserIsMutable();
          pUser_.add(index, builderForValue.build());
          onChanged();
        } else {
          pUserBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PuzzleGameUserInfo pUser = 2;</code>
       */
      public Builder addAllPUser(
          java.lang.Iterable<? extends com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo> values) {
        if (pUserBuilder_ == null) {
          ensurePUserIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, pUser_);
          onChanged();
        } else {
          pUserBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .PuzzleGameUserInfo pUser = 2;</code>
       */
      public Builder clearPUser() {
        if (pUserBuilder_ == null) {
          pUser_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          pUserBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .PuzzleGameUserInfo pUser = 2;</code>
       */
      public Builder removePUser(int index) {
        if (pUserBuilder_ == null) {
          ensurePUserIsMutable();
          pUser_.remove(index);
          onChanged();
        } else {
          pUserBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .PuzzleGameUserInfo pUser = 2;</code>
       */
      public com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo.Builder getPUserBuilder(
          int index) {
        return getPUserFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .PuzzleGameUserInfo pUser = 2;</code>
       */
      public com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfoOrBuilder getPUserOrBuilder(
          int index) {
        if (pUserBuilder_ == null) {
          return pUser_.get(index);  } else {
          return pUserBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .PuzzleGameUserInfo pUser = 2;</code>
       */
      public java.util.List<? extends com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfoOrBuilder> 
           getPUserOrBuilderList() {
        if (pUserBuilder_ != null) {
          return pUserBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(pUser_);
        }
      }
      /**
       * <code>repeated .PuzzleGameUserInfo pUser = 2;</code>
       */
      public com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo.Builder addPUserBuilder() {
        return getPUserFieldBuilder().addBuilder(
            com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .PuzzleGameUserInfo pUser = 2;</code>
       */
      public com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo.Builder addPUserBuilder(
          int index) {
        return getPUserFieldBuilder().addBuilder(
            index, com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .PuzzleGameUserInfo pUser = 2;</code>
       */
      public java.util.List<com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo.Builder> 
           getPUserBuilderList() {
        return getPUserFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo, com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo.Builder, com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfoOrBuilder> 
          getPUserFieldBuilder() {
        if (pUserBuilder_ == null) {
          pUserBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo, com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfo.Builder, com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameUserInfoOrBuilder>(
                  pUser_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          pUser_ = null;
        }
        return pUserBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:PuzzleGameMessage)
    }

    // @@protoc_insertion_point(class_scope:PuzzleGameMessage)
    private static final com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage();
    }

    public static com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<PuzzleGameMessage>
        PARSER = new com.google.protobuf.AbstractParser<PuzzleGameMessage>() {
      public PuzzleGameMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new PuzzleGameMessage(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<PuzzleGameMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PuzzleGameMessage> getParserForType() {
      return PARSER;
    }

    public com.pcer.puzzlegame.proto.PuzzleGameProto.PuzzleGameMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PuzzleGameUserInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PuzzleGameUserInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PuzzleGameMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PuzzleGameMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025PuzzleGameProto.proto\"Z\n\022PuzzleGameUse" +
      "rInfo\022\020\n\010username\030\001 \001(\t\022\020\n\010nickname\030\002 \001(" +
      "\t\022\020\n\010password\030\003 \001(\t\022\016\n\006scores\030\004 \001(\005\"\216\002\n\021" +
      "PuzzleGameMessage\022+\n\007mesType\030\001 \002(\0162\032.Puz" +
      "zleGameMessage.MesType\022\"\n\005pUser\030\002 \003(\0132\023." +
      "PuzzleGameUserInfo\"\247\001\n\007MesType\022\n\n\006REGREQ" +
      "\020\000\022\n\n\006REGACK\020\001\022\n\n\006REGNEG\020\002\022\n\n\006LOGREQ\020\003\022\n" +
      "\n\006LOGACK\020\004\022\n\n\006LOGNEG\020\005\022\n\n\006SUBREQ\020\006\022\n\n\006SU" +
      "BACK\020\007\022\013\n\007RANKREQ\020\010\022\013\n\007RANKACK\020\t\022\n\n\006MODR" +
      "EQ\020\n\022\n\n\006MODACK\020\013\022\n\n\006MODNEG\020\014B,\n\031com.pcer",
      ".puzzlegame.protoB\017PuzzleGameProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PuzzleGameUserInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PuzzleGameUserInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PuzzleGameUserInfo_descriptor,
        new java.lang.String[] { "Username", "Nickname", "Password", "Scores", });
    internal_static_PuzzleGameMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PuzzleGameMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PuzzleGameMessage_descriptor,
        new java.lang.String[] { "MesType", "PUser", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
